#config-version=FGT50G-7.6.7-FW-build3704-260101:opmode=0:vdom=0:user=admin
#conf_file_ver=1
#buildno=3704
#global_vdom=1
config system global
    set hostname "LAB-FGT"
end
config firewall address
    edit "apple-probe"
        set type fqdn
        set fqdn "captive.apple.com"
    next
    edit "android-probe"
        set type fqdn
        set fqdn "connectivitycheck.gstatic.com"
    next
    edit "login.microsoftonline.com"
        set type fqdn
        set fqdn "login.microsoftonline.com"
    next
end
config firewall addrgrp
    edit "probe-group"
        set member "android-probe"
    next
end
config vpn certificate local
    edit "portal-cert"
        set password ENC dummy
        set certificate "-----BEGIN CERTIFICATE-----
MIIBODCB4KADAgECAhRdUMQesQeyrv3TUqC2EQKH/QmOMzAKBggqhkjOPQQDAjAd
MRswGQYDVQQDDBJwb3J0YWwubGFiLmV4YW1wbGUwHhcNMjUxMTAxMDAwMDAwWhcN
MjYxMTAzMDAwMDAwWjAdMRswGQYDVQQDDBJwb3J0YWwubGFiLmV4YW1wbGUwWTAT
BgcqhkjOPQIBBggqhkjOPQMBBwNCAAQwt4k3uDitzUSF3aRrRQcAmsNUooQnIRJB
P4L1c24VgU7NEPAQhzP90Q+mY5+7JA1Yy5okTB1+Yf5NRg+o0mR4MAoGCCqGSM49
BAMCA0cAMEQCIDroIYCzCwrUOkojmUw3DJMPRziuCVdDxGD0Igz+jdNVAiAOES1y
RGbPIC65+wmJBHJKq5RjlAXsOQT6FYWJ8awGTg==
-----END CERTIFICATE-----"
    next
end
config user saml
    edit "entra-portal"
        set entity-id "https://10.10.20.1:1003/remote/saml/metadata/"
        set single-sign-on-url "https://10.10.20.1:1003/remote/saml/login/"
        set single-logout-url "https://10.10.20.1:1003/remote/saml/logout/"
        set idp-entity-id "https://sts.windows.net/00000000-0000-0000-0000-000000000000/"
    next
end
config user security-exempt-list
    edit "guest-exempt"
        config rule
            edit 1
                set dstaddr "login.microsoftonline.com" "apple-probe" "probe-group"
            next
        end
    next
end
config wireless-controller vap
    edit "guest"
        set ssid "LAB-GUEST"
        set security captive-portal
        set security-exempt-list "guest-exempt"
        set security-redirect-url "https://www.example.com"
    next
end
config vpn ipsec phase1-interface
    edit "to-branch"
        set interface "wan1"
        set ike-version 2
        set peertype any
        set remote-gw 203.0.113.10
        set psksecret ENC dummy
    next
    edit "RA_VPN"
        set type dynamic
        set interface "wan1"
        set mode aggressive
        set peertype any
        set xauthtype auto
        set psksecret ENC dummy
    next
end
config vpn ipsec phase2-interface
    edit "to-branch-srv1"
        set phase1name "to-branch"
        set src-subnet 10.10.10.5 255.255.255.255
        set dst-subnet 172.16.5.11 255.255.255.255
    next
    edit "to-branch-srv2"
        set phase1name "to-branch"
        set src-subnet 10.10.10.5 255.255.255.255
        set dst-subnet 172.16.5.12 255.255.255.255
    next
    edit "to-branch-srv3"
        set phase1name "to-branch"
        set auto-negotiate enable
        set src-subnet 10.10.10.5 255.255.255.255
        set dst-subnet 172.16.5.13 255.255.255.255
    next
    edit "RA_VPN"
        set phase1name "RA_VPN"
    next
end
config router static
    edit 1
        set gateway 198.51.100.1
        set device "wan1"
    next
    edit 2
        set gateway 192.0.2.1
        set device "wan2"
    next
end
