#config-version=FGT50G-7.6.7-FW-build3704-260101:opmode=0:vdom=0:user=admin
config system global
    set hostname "LAB-FGT-CLEAN"
end
config vpn certificate local
    edit "portal-cert"
        set certificate "-----BEGIN CERTIFICATE-----
MIIBOTCB4KADAgECAhQNfFk7/OxRNaKAvSkv/XFTifUK2DAKBggqhkjOPQQDAjAd
MRswGQYDVQQDDBJwb3J0YWwubGFiLmV4YW1wbGUwHhcNMjUxMTAxMDAwMDAwWhcN
MjgxMTAzMDAwMDAwWjAdMRswGQYDVQQDDBJwb3J0YWwubGFiLmV4YW1wbGUwWTAT
BgcqhkjOPQIBBggqhkjOPQMBBwNCAASvl85+IWZR1Bw+cytUrTR/cwniUVq8U5gP
MDKXa5j63CNj0DJQZCvMFNLZp/0AeugMJf6OSn5GISJu8z8SF1INMAoGCCqGSM49
BAMCA0gAMEUCIBqRk5rYf4+CibDwXIoSd6ocEMhgkP63V2CB9FS8B1PQAiEA696I
9WDZipa8aerK6fS9ouinkybQA0zb9/rfNquQSFk=
-----END CERTIFICATE-----"
    next
end
config user saml
    edit "entra-portal"
        set entity-id "https://portal.lab.example:1003/remote/saml/metadata/"
        set single-sign-on-url "https://portal.lab.example:1003/remote/saml/login/"
    next
end
config vpn ipsec phase1-interface
    edit "to-branch"
        set interface "wan1"
        set ike-version 2
        set remote-gw 203.0.113.10
        set dpd on-idle
    next
    edit "RA_VPN"
        set type dynamic
        set interface "wan1"
        set ike-version 2
    next
end
config vpn ipsec phase2-interface
    edit "to-branch"
        set phase1name "to-branch"
        set auto-negotiate enable
        set src-subnet 10.10.10.0 255.255.255.0
        set dst-subnet 172.16.5.0 255.255.255.240
    next
end
config router static
    edit 1
        set gateway 198.51.100.1
        set device "wan1"
    next
    edit 2
        set gateway 192.0.2.1
        set device "wan2"
        set distance 20
    next
end
